### ISSUE TITLE
forRoot bug ERROR Function calls are not supported in decorators but 'CacheModule' was called.

### ISSUE THREAD

**Issue by vasilvalkov** [Stradivario/ngx-cache-layer#1]
versions
``` json
"@angular/core": "^7.2.12",
"@angular/compiler": "^7.2.12",
"@angular/cli": "^7.3.8",
"@angular/compiler-cli": "^7.2.12",
"@rxdi/cache": "^3.0.0"
```

CoreModule:
``` JavaScript
import { CommonModule } from '@angular/common';
import { CacheModule } from '@rxdi/cache';

@NgModule({
  imports: [
    CommonModule,
    CacheModule.forRoot({ localStorage: true })
  ]
})
export class CoreModule {}
```

command
`ng build --prod --aot --extractLicenses=true`

error:

> ERROR in Error during template compile of 'CoreModule'
>   Function calls are not supported in decorators but 'CacheModule' was called.

**Comment by Stradivario** [comment]
I am having the same issue since Angular 7+ yesterday i try to fix it with no success. My `stupid` work around is to copy src files and use it like an regular internal angular module instead installing it from node_modules.I am curious what create this bug ? Ivy compiler ? new AOT compilation ? 

hmm....

@vasilvalkov

**Comment by vasilvalkov** [comment]
I've read here and there about this issue and tried some things with no success. Probably the cause for this issue is in the factory function that is used for providing the CACHE_MODULE_CONFIG token. It probably should be a static value as described here  [angular/angular#23609 (comment)](https://github.com/angular/angular/issues/23609#issuecomment-417142142).

Additionally, I installed the old package `ngx-cache-layer@1.6.2` and it worked with no error. In this old package the CACHE_MODULE_CONFIG token is provided with `useValue`.

**Comment by Stradivario** [comment]
@vasilvalkov today i will make pull request with working version i think i know from where it is coming from. 1.6.2 i think it is with old syntax RXJS 5 so you will need to use rxjs-compat which is not really awesome.

**Comment by Stradivario** [comment]
@vasilvalkov merged your pull request ! Thank you very much for that :) I appreciate it !

Since i cannot login with this account which publish `ngx-cache-layer` at the first time this repository is deprecated and all changes are added here

```
### Deprecated in favor of https://github.com/rxdi/cache
```

`@rxdi/cache@3.0.1` - published to npm with your pull request included.

Please let me know if you have any problems.
I will create some tests today so we will have consistency of what we are doing. 

Regards!
